### ISSUE TITLE
Mod not working 

### ISSUE THREAD

**Issue by razvy2632** [Parik27/V.Rainbomizer#22]
Hello. I have an issue that is really frustrating.
I tried with both Steam and Epic Games versions of GTAV installing this mod. It doesn't work with neither of the games. I tried with the entire folder of the mod, and with the content of the folder of Rainbomizer inside the game. I want to say that the ScriptHookV is installing and working because the NativeTrainer opens.

**Comment by Parik27** [comment]
It's preferable to keep installation issues on the Discord server or Discussions and use the Issues tab for softlocks/crashes/feature requests, but I'll respond to your issue here.

Another thing that's really frustrating is that you don't mention any other details except that it doesn't work. 

But either way, it seems that you downloaded the source code instead of the binary 7z file from Releases as mentioned in the installation instructions.

This is how your directory should look:
<img src="https://media.discordapp.net/attachments/821138024192278640/870720031837798400/unknown.png">

**Comment by razvy2632** [comment]
Thank you very much for your answer. 
I am glad that an open-source project like this exists. It makes a really big game so much funny and interesting. As a programming instructor, I say to you guys that y'all did an amazing job and I thing all the users thank you for your abilites and good inspiration
