### ISSUE TITLE
[FEAT] Randomize mission destinations

### ISSUE THREAD

**Issue by Katsute** [Parik27/V.Rainbomizer#29]
Randomize where you have to drive to on missions

**Comment by Parik27** [comment]
Not a simple thing to implement, you'd need to go through every single mission's code and modify the destinations there. Not to mention the game has 'abandoned' checks which fail the mission when you leave an area which would also need to be modified. Furthermore, the cutscenes will also have to be moved because otherwise the characters will despawn if the two locations are far-enough apart. There are a lot of factors that make implementing this nearly impossible without rewriting the entire game's storyline.
