### ISSUE TITLE
Skin suit and invisible body parts

### ISSUE THREAD

**Issue by CatGirlCarGirl** [Parik27/V.Rainbomizer#31]
Sometimes npcs or player will spawn with face textures on torso and legs. other times will spawn with invisible parts i.e. no legs etc.

**Comment by Parik27** [comment]
Not sure why that would be an issue, it doesn't cause any softlocks or other problematic situations in the game as far as I'm aware.

**Comment by CatGirlCarGirl** [comment]
I just assumed that it was a bug in the mod and wasnt sure if you were aware of it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Parik27** [comment]
It's caused by the game assigning an invalid component/texture variation to a ped. (so basically an outfit that exists for the original ped but not for the randomized ped). Not completely sure it's worth fixing, but an Outfit Randomizer that's planned for the future will likely fix it by getting rid of the invalid outfits.

**Comment by CatGirlCarGirl** [comment]
Thankyou for taking the time to explain that to me.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
